# Generated by Django 3.2.6 on 2021-09-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='numero_ext',
            field=models.IntegerField(max_length=25),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='numero_int',
            field=models.IntegerField(max_length=25),
        ),
    ]
