# Generated by Django 3.2.6 on 2021-09-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20210901_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='numero_ext',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='numero_int',
            field=models.IntegerField(),
        ),
    ]
