# Generated by Django 3.2.6 on 2021-09-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20210901_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocupacion',
            old_name='sociales',
            new_name='email',
        ),
    ]
